<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="en" sourcelanguage="en">
<context>
    <name></name>
    <message id="invalid-api-url">
        <location filename="../src/API/component.cpp" line="+94"/>
        <source>Invalid API URL</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-conn-timeout" numerus="yes">
        <location line="+116"/>
        <source>The connection to the server timed out after %n second(s).</source>
        <translation type="unfinished">
            <numerusform></numerusform>
            <numerusform></numerusform>
        </translation>
    </message>
    <message id="id-err-no-config">
        <location line="+24"/>
        <location filename="../src/Helpers/accountvalidator.cpp" line="+68"/>
        <source>No configuration available.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-username-pass-missing">
        <location line="+7"/>
        <source>You have to specify a username and a password.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-no-host">
        <location line="+7"/>
        <source>No host specified</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-no-route">
        <location line="+7"/>
        <source>No API route specified.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-no-payloud">
        <location line="+7"/>
        <source>Empty payload when trying to perform a PUT or POST network operation.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-empty-answer">
        <location line="+26"/>
        <source>The request replied an empty answer, but there was content expected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-no-json-array">
        <location line="+7"/>
        <source>It was expected that the request returns a JSON array, but it returned something else.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-no-json-object">
        <location line="+7"/>
        <source>It was expected that the request returns a JSON object, but it returned something else.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-1">
        <location filename="../src/error.cpp" line="+68"/>
        <source>The remote server at %1 refused the connection.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-2">
        <location line="+4"/>
        <source>The remote server at %1 closed the connection prematurely, before the entire reply was received and processed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-3">
        <location line="+4"/>
        <source>The remote host name %1 was not found.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-4">
        <location line="+4"/>
        <source>The connection to the server at %1 timed out.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-5">
        <location line="+4"/>
        <source>The operation was canceled before it was finished.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-6">
        <location line="+4"/>
        <source>The SSL/TLS handshake failed and the encrypted channel could not be established.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-7">
        <location line="+4"/>
        <source>The connection was broken due to disconnection from the network.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-8">
        <location line="+4"/>
        <source>The connection was broken due to disconnection from the network or failure to start the network.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-9">
        <location line="+4"/>
        <source>The background request is not currently allowed due to platform policy.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-10">
        <location line="+5"/>
        <source>While following redirects, the maximum limit was reached.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-11">
        <location line="+4"/>
        <source>While following redirects, the network access API detected a redirect from an encrypted protocol (https) to an unencrypted one (http).</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-101">
        <location line="+5"/>
        <source>The connection to the proxy server was refused (the proxy server is not accepting requests).</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-102">
        <location line="+4"/>
        <source>The proxy server closed the connection prematurely, before the entire reply was received and processed.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-103">
        <location line="+4"/>
        <source>The proxy host name was not found (invalid proxy hostname).</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-104">
        <location line="+4"/>
        <source>The connection to the proxy timed out or the proxy did not reply in time to the request sent</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-105">
        <location line="+4"/>
        <source>The proxy requires authentication in order to honour the request but did not accept any credentials offered (if any).</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-201">
        <location line="+4"/>
        <source>The access to the remote content was denied.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-202">
        <location line="+4"/>
        <source>The operation requested on the remote content is not permitted.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-203">
        <location line="+4"/>
        <source>The remote content was not found at the server.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-204">
        <location line="+4"/>
        <source>The remote server requires authentication to serve the content but the credentials provided were not accepted (if any).</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-205">
        <location line="+4"/>
        <source>The request needed to be sent again, but this failed for example because the upload data could not be read a second time.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-206">
        <location line="+5"/>
        <source>The request could not be completed due to a conflict with the current state of the resource.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-207">
        <location line="+4"/>
        <source>The requested resource is no longer available at the server.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-401">
        <location line="+4"/>
        <source>The server encountered an unexpected condition which prevented it from fulfilling the request.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-402">
        <location line="+4"/>
        <source>The server does not support the functionality required to fulfill the request.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-403">
        <location line="+4"/>
        <source>The server is unable to handle the request at this time.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-301">
        <location line="+5"/>
        <source>The Network Access API cannot honor the request because the protocol is not known.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-302">
        <location line="+4"/>
        <source>The requested operation is invalid for this protocol.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-99">
        <location line="+4"/>
        <source>An unknown network-related error was detected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-199">
        <location line="+4"/>
        <source>An unknown proxy-related error was detected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-299">
        <location line="+4"/>
        <source>An unknown error related to the remote content was detected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-399">
        <location line="+4"/>
        <source>A breakdown in protocol was detected (parsing error, invalid or unexpected responses, etc.).</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-net-reply-499">
        <location line="+5"/>
        <location line="+5"/>
        <source>An unknown error related to the server response was detected.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="id-err-version-low-status-user">
        <location filename="../src/Helpers/accountvalidator.cpp" line="+21"/>
        <source>The version of your News App is lower than 5.2.4. Status and user information can not be queried.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="id-err-version-low-user">
        <location line="+21"/>
        <source>The version of your News App is lower than 6.0.5. User information can not be queried.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-version-not-found">
        <location filename="../src/API/getstatus.cpp" line="+102"/>
        <location filename="../src/API/getversion.cpp" line="+99"/>
        <source>Can not find the version information in the server reply.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-warnings-not-found">
        <location line="+7"/>
        <source>Can not find the warnings information in the server reply.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="err-displayname-not-found">
        <location filename="../src/API/getuser.cpp" line="+107"/>
        <source>Can not find the user&apos;s display name in the server reply.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="libfuoten-err-failed-open-db">
        <location filename="../src/Storage/sqlitestorage.cpp" line="+63"/>
        <location line="+95"/>
        <source>Failed to open the SQLite database.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="fuoten-error-failed-execute-query">
        <location line="-83"/>
        <location line="+16"/>
        <location line="+13"/>
        <location line="+16"/>
        <location line="+7"/>
        <location line="+162"/>
        <location line="+24"/>
        <location line="+26"/>
        <location line="+74"/>
        <source>Failed to execute database query.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="fuoten-error-transaction-begin">
        <location line="-332"/>
        <location line="+196"/>
        <source>Failed to begin a database transaction.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="fuoten-error-transaction-commit">
        <location line="-167"/>
        <location line="+239"/>
        <source>Failed to commit a database transaction.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="libfuoten-err-sqlite-db-not-ready">
        <location line="-176"/>
        <source>SQLite database not ready. Can not process requested data.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="fuoten-failed-query-folders">
        <location line="+30"/>
        <source>Failed to query the folders from the local database.</source>
        <translation type="unfinished"></translation>
    </message>
    <message id="fuoten-error-failed-prepare-query">
        <location line="+101"/>
        <location line="+26"/>
        <source>Failed to prepare database query.</source>
        <translation type="unfinished"></translation>
    </message>
</context>
</TS>
